### ISSUE TITLE
How to let UICollectionView focus on to the first visible UICollectionViewCell instead of the first UICollectionViewCell?

### ISSUE THREAD

**Issue by evayuhz** [dequelabs/Deque-University-for-iOS#42]
There is a UICollectionView in ViewController, and it's scroll direction is horizontal, and each UICollectionViewCell's size is equal to the screen size.

### Inaccessible Behavior

1. When I put VoiceOver focus on navigation title
2. Then swipe right
3. Focus moves to the first cell of the collection view, instead of the current visible cell.

### Accessible Behavior

Focus should moves to the current visible cell of the collection view.

### Attest html file

[CollectionViewAccessibility.html.zip](https://github.com/dequelabs/Deque-University-for-iOS/files/2423087/CollectionViewAccessibility.html.zip)

**Comment by chriscm2006** [comment]
Discussed this with @evayuhz, will add notes and check back before I close this one out!

**Comment by chriscm2006** [comment]
In this case I think the **Accessible Behavior** description is misguided. What we have here is essentially an infinitely scrolling carousel. The more images a user has in their collection, the longer the list of potential focus targets is. 

### Potential Solution: Do Nothing

I believe the answer to the general question is legitimately, don't do this. If it's not impossible, it adds very little value over doing nothing. The infinite scroll issue still exists, which is a much more critical accessibility issue. 

### Real Solution: Implement Carousel Scrolling Using Adjustable Trait

Instead of forcing focus around, and allowing the "Carousel" to be browsed by focus gestures, we should implement this in a completely different way. Instead of scrolling through focusable items on swipe navigation gestures, treat the entire CollectionView as one focusable element, and scroll through elements using the increment/decrement callbacks of the Adjustable trait.

We will implement this in a Demo. Follow Issue #43 for updates and documentation.

**Comment by chriscm2006** [comment]
We will implement this in a Demo. 

Follow Issue #43 for updates and documentation.
