### ISSUE TITLE
Problem running the test project

### ISSUE THREAD

**Issue by avladut** [dequelabs/Deque-University-for-iOS#50]
Hello, 
I'm trying to run the test project using XCode 9.2, and this is my bash profile:

> export DEQUE_ANON_APIKEY=...
> export DEQUE_ATTEST_IOS_VERSION=1.3.1
> export DEQUE_ATTEST_XCODE_VERSION=9.2

I'm getting an error when trying to build the app:

```
Attest Failed to Download

"Xcode9.2" should match one of the URIs below (Except the /)

If your exact Xcode version isn't available you can override this in your bash_profile.

For example for Xcode 9.3.1 a proper bash_profile entry would be

export DEQUE_ATTEST_XCODE_VERSION=Xcode9.3

Also "1.3.1" should be available in the list below.

The following artifacts are available for Xcode9.2

If you're having trouble accessing an Attest framework bundle for your Xcode Version please contact helpdesk@deque.com

Command /bin/sh failed with exit code 1

```
Has anyone else encountered the issue?

**Comment by chriscm2006** [comment]
@jldailey13 The confusing part here for me is the lack of JSON/supported versions between

> "Xcode9.2" should match one of the URIs below (Except the /)

and

> If your exact Xcode version isn't available you can override this in your bash_profile.

@avladut There is a curl [here](https://github.com/dequelabs/Deque-University-for-iOS/blob/23c552dc8b8d1e80a38fd86bfccc9d6a988b2339/Scripts/CurlFramework.sh#L66) that seems to be failing silently. Any additional information you can supply would be helpful, but we can attempt to replicate.

**Comment by chriscm2006** [comment]
PR #53 should enable more error messaging. This at the very least, should make the reasons behind the issue more clear. That it could fail silently before was not ideal. Without more information this issue is blocked. If this resolution is good enough, give me a thumbs up on this comment! Otherwise, we await more information. 

Note: Items blocked for more than a week due to lack of information will be closed.
